. /etc/profile

# Proxmox
PM_USER=$(pass hideOut/Terraform/Proxmox/user)
PM_PASS=$(pass hideOut/Terraform/Proxmox/pass)

# Terraform

# Fortis Games
NEXUS_USER=$(pass Fortis/Nexus/user)
NEXUS_PASS=$(pass Fortis/Nexus/pass)
NPM_TOKEN=$(pass Fortis/Nexus/NPM_Token)
